# Application server ID
passwordless.corpId = 1d09c146d35c45d3ab62f750737fdb98
passwordless.serverId = 1d09c146d35c45d3ab62f750737fdb98


# Application server key (Only displayed once when changed)
passwordless.serverKey = 6be6f8054a84146f


# URL to go to Simple UI screen (passwordless server - nginx)
passwordless.simpleAutopasswordUrl = http://192.168.0.31:8080


# Authentication server domain
passwordless.restCheckUrl = http://192.168.0.31:11040


# Push request server to connect to Websocket
passwordless.pushConnectorUrl = ws:192.168.0.31:15010


# Passwordless Recommended Specifications (ID/Password login prohibited when registering Passwordless) - 1: Applied, 0: Not Applied
passwordless.recommend = 1
